shuffle_train = False
train_eval_random_subset = True
RELATIONTYPE_AMOUNT = 2
ENTITYTYPE_AMOUNT =  5000
FACTS_PER_RELATION = 10000
NUMBER_RULES = 1
MAX_INSTANCES_PER_FACT = 1
ratio_of_pattern_relations = 0.5  # percentage of relations that show the specific pattern
ratio_of_complete_patterns = 0.5  # for the relations that show pattern, how many patterns are complete in training
